webapps_directory: "/var/www/workspace42"
backup_directory: "/var/www/workspace42/webf-backups"
log_to_file: true
log_file: "/var/www/workspace42/webf-backups/backup_log.txt"
log_to_stdout: true
tarsnap: true
targz: true
