webapps_directory: "$HOME/workspace42"
backup_directory: "$HOME/webf-backups"
log_to_file: true
log_file: "$HOME/webf-backups/backup_log.txt"
log_to_stdout: false
tarsnap: true
tarsnap_bin: "$HOME/bin/tarsnap"
targz: false
