webapps_directory: "/home/[username]/webapps"
backup_directory: "/home/[username]/webf-backups"
log_to_file: true
log_file: "/home/[username]/webf-backups/backup_log.txt"
log_to_stdout: false
tarsnap: true
tarsnap_bin: "/home/[username]/bin/tarsnap"
targz: false
